feat[measure-time-app]: add common files + create html/css structure for app
romashka-dev/prjctr-time-measure-diploma pull request #1
Opened 2023-06-10 16:53 UTC by romashka-dev

2023-07-05 16:21 UTC, myroslav-kolomiiets requested changes

2023-07-05 16:21 UTC, myroslav-kolomiiets commented on src/index.js
> +  return startDateValue;
```suggestion
  return new Date(startDate.value);
```

2023-07-05 16:21 UTC, myroslav-kolomiiets commented on src/index.js
> +  return startDateValue;
Не варто створювати непотрібні змінні, вона ніде не використовується більше

2023-07-05 16:21 UTC, myroslav-kolomiiets commented on src/index.js
> +  return endDateValue;
Те ж саме

2023-07-05 16:21 UTC, myroslav-kolomiiets commented on src/index.js
> +  resultArea.value = result;
Баг описаний в коментарі виникає, тому що текст з функції setDatesAtInputs, перетирається тут пустим рядком

2023-07-05 16:21 UTC, myroslav-kolomiiets commented on src/index.js
> +    return;
Цей return нічого не повертає і виходити з функції по умові не має сенсу, тому, що далі немає ніякого коду

2023-07-05 16:21 UTC, myroslav-kolomiiets commented on src/index.js
> +const checkEndDate = () => {
У користувача не повинно бути можливості вибрати дату раніше, тому тут краще піти шляхом модифікації атрибутів в input type date (min)

2023-07-05 16:21 UTC, myroslav-kolomiiets commented on src/index.js
> +    if (presetSelect.value === 'week') {
Тут якраз краще switch

2023-07-05 16:21 UTC, myroslav-kolomiiets commented on src/index.js
> +const checkEndDate = () => {
І таким чином, можна буде прибрати цю функцію, а також getStartDateValue і getEndDateValue

2023-07-12 20:27 UTC, romashka-dev commented on src/index.js
> +  return startDateValue;
Зробив зміни.

2023-07-12 20:27 UTC, romashka-dev commented on src/index.js
> +  return endDateValue;
Зробив зміни.

2023-07-12 20:28 UTC, romashka-dev commented on src/index.js
> +  resultArea.value = result;
Пофіксив.

2023-07-12 20:28 UTC, romashka-dev commented on src/index.js
> +    return;
Видалив return, зрозуміло.

2023-07-12 20:36 UTC, romashka-dev commented on src/index.js
> +const checkEndDate = () => {
Не дуже зрозумів пропозицію за допомогою "модифікації  атрибутів в input type date (min)", тому залишив поточний підхід.

2023-07-12 20:36 UTC, romashka-dev commented on src/index.js
> +    if (presetSelect.value === 'week') {
Зробив зміни.

2023-07-12 20:40 UTC, merged